export const LOGIN_EMAIL_CHANGE = 'LOGIN_EMAIL_CHANGE'
export const LOGIN_PASSWORD_CHANGE = 'LOGIN_PASSWORD_CHANGE'
// export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_SUCESS = 'LOGIN_USER_SUCESS'